//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FourthDay.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Carriages
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Carriages()
        {
            this.Repair = new HashSet<Repair>();
        }
    
        public double RegNumber { get; set; }
        public string RegName { get; set; }
        public string RegCheif { get; set; }
        public int TypeID { get; set; }
        public short Year { get; set; }
        public byte[] Picture { get; set; }
    
        public virtual CarriageTypes CarriageTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Repair> Repair { get; set; }
    }
}
