//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FourthDay.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeesInGroup
    {
        public int ID { get; set; }
        public int GroupID { get; set; }
        public int EmployeeID { get; set; }
        public bool Cheif { get; set; }
    
        public virtual Employees Employees { get; set; }
        public virtual Groups Groups { get; set; }
    }
}
